@Aurora.IssuesService.Host_HostAddress = http://localhost:7201

### Issues

GET {{Aurora.IssuesService.Host_HostAddress}}/api/issues

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/issues?status=Closed

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/issues?versionId=1

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/issues?versionId=0

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/issues?status=Closed&versionId=1

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/issues
Content-Type: application/json

{
  "title": "Issue {{$randomInt}}",
  "description": "Description of issue is {{$guid}}."
}

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/issues
Content-Type: application/json

{
  "title": "Issue {{$randomInt}}",
  "description": "Description of issue is {{$guid}}.",
  "versionId": 1
}

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/issues
Content-Type: application/json

{
  "title": "Issue {{$randomInt}}",
  "description": "Description of issue is {{$guid}}.",
  "versionId": 0
}

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/issues
Content-Type: application/json

{
  "description": "Description of issue is {{$guid}}."
}

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/issues/1

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/issues/0

###

PUT {{Aurora.IssuesService.Host_HostAddress}}/api/issues/1
Content-Type: application/json

{
  "title": "Issue {{$randomInt}}",
  "description": "Description of issue is {{$guid}}.",
  "status": "Closed"
}

###

PUT {{Aurora.IssuesService.Host_HostAddress}}/api/issues/1
Content-Type: application/json

{
  "title": "Issue {{$randomInt}}",
  "description": "Description of issue is {{$guid}}.",
  "status": "Closed",
  "versionId": 1
}

###

PUT {{Aurora.IssuesService.Host_HostAddress}}/api/issues/1
Content-Type: application/json

{
  "title": "Issue {{$randomInt}}",
  "description": "Description of issue is {{$guid}}.",
  "status": "Closed",
  "versionId": 0
}

### Versions

GET {{Aurora.IssuesService.Host_HostAddress}}/api/versions

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/versions/1

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/versions/0

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/versions
Content-Type: application/json

{
  "name": "Version {{$guid}}"
}

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/versions
Content-Type: application/json

{
}

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/versions
Content-Type: application/json

{
  "name": "Version - Duplicate"
}

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/versions
Content-Type: application/json

{
  "name": "   "
}

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/versions
Content-Type: application/json

{
  "name": "   Version {{$guid}}   "
}

###

PUT {{Aurora.IssuesService.Host_HostAddress}}/api/versions/1
Content-Type: application/json

{
  "name": "Version {{$guid}}"
}

###

PUT {{Aurora.IssuesService.Host_HostAddress}}/api/versions/0
Content-Type: application/json

{
  "name": "Version {{$guid}}"
}

###

PUT {{Aurora.IssuesService.Host_HostAddress}}/api/versions/1
Content-Type: application/json

{
}

###

PUT {{Aurora.IssuesService.Host_HostAddress}}/api/versions/1
Content-Type: application/json

{
  "name": "Version - Duplicate"
}

###

PUT {{Aurora.IssuesService.Host_HostAddress}}/api/versions/1
Content-Type: application/json

{
  "name": "   "
}

###

PUT {{Aurora.IssuesService.Host_HostAddress}}/api/versions/2
Content-Type: application/json

{
  "name": "   Version {{$guid}}   "
}

### Issues/Checklists

GET {{Aurora.IssuesService.Host_HostAddress}}/api/issues/18/checklists

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/issues/18/checklists
Content-Type: application/json

{
  "title": "Checklist - {{$guid}}"
}

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/issues/0/checklists
Content-Type: application/json

{
  "title": "Checklist - {{$guid}}"
}

###

PUT {{Aurora.IssuesService.Host_HostAddress}}/api/checklists/1
Content-Type: application/json

{
  "title": "Checklist - {{$guid}}"
}

###


PUT {{Aurora.IssuesService.Host_HostAddress}}/api/checklists/0
Content-Type: application/json

{
  "title": "Checklist - {{$guid}}"
}

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/checklists/1/items
Content-Type: application/json

{
  "content": "Checklist item - {{$guid}}"
}

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/checklists/0/items
Content-Type: application/json

{
  "content": "Checklist item - {{$guid}}"
}

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/checklists/1

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/checklists/0

###