@Aurora.IssuesService.Host_HostAddress = http://localhost:7201

GET {{Aurora.IssuesService.Host_HostAddress}}/api/issues

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/issues?status=Closed

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/issues
Content-Type: application/json

{
  "title": "Issue {{$randomInt}}",
  "description": "Description of issue is {{$guid}}."
}

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/issues
Content-Type: application/json

{
  "description": "Description of issue is {{$guid}}."
}

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/issues/1

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/issues/0

###

PUT {{Aurora.IssuesService.Host_HostAddress}}/api/issues/1
Content-Type: application/json

{
  "title": "Issue {{$randomInt}}",
  "description": "Description of issue is {{$guid}}.",
  "status": "Closed"
}

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/versions/1

###

GET {{Aurora.IssuesService.Host_HostAddress}}/api/versions/0

###

POST {{Aurora.IssuesService.Host_HostAddress}}/api/versions
Content-Type: application/json

{
  "name": "Version {{$guid}}"
}

###
