name: dev-aurora
services:
  services.issues-service:
    profiles:
      - services
    image: aurora.services.issues-service:latest
    build: ../src/services/issues-service
    volumes:
      - issues-service-storage:/app/storage
    environment:
      AURORA_ISSUES_DB_PATH: "storage/issues-db.json"
    ports:
      - "7201:8201"
    
  web:
    profiles:
      - web
    image: aurora.web:latest
    build: ../src/web
    ports:
      - "7100:8100"

volumes:
  issues-service-storage: